vfs_pool_size = 8

[allocator]
read_buffer_size = 65536
read_buffer_count = 4096
write_buffer_size = 65536
write_buffer_count = 4096

[uring]
ring_count = 4
ring_size = 2048

[exports]
root = "/tmp/nfs"
paths = ["fs01", "fs02"]
