name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustfmt Check
        run: cargo fmt --all --check

  cargo-clippy:
    needs: cargo-fmt
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clippy Check
        run: cargo clippy -- -Dwarnings

  cargo-build:
    needs: cargo-clippy
    name: Cargo build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo build
        run: cargo build

  cargo-test:
    needs: cargo-build
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo test
        run: cargo test

  cargo-doc:
    needs: cargo-test
    name: Cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo doc test
        run: cargo doc

